### ISSUE TITLE
Failed to load models: The unidic_lite dictionary is not installed. See https://github.com/polm/unidic-lite for installation.

### ISSUE THREAD

**Issue by Panwar0** [Crivella/ocr_extension#7]
***PLEASE REPLY ASAP! AND THANKS FOR THIS WONDERFUL PROJECT!!!***
hey, I'm getting the same error, it's getting me hella confused and I'm constantly rubbing my hand what the hell man.

i am using win 10

Failed to load models: The unidic_lite dictionary is not installed. See https://github.com/polm/unidic-lite for installation.

any solutions? i already installed separately unidic-lite, fugashi, mecab-python3 reply asap please!!!

i selected jp to eng (it is green) as suggested by you i used the same model but after submitting model shows this unidic error!!

it is similar to this issue:
https://github.com/Crivella/ocr_extension/issues/4

**Comment by Crivella** [comment]
The latest version of the server takes the python packages from a venv that is created in the folder with the `run-user` script + the `plugins` folder under `OCT_BASE_DIR` (the server writes the path to this when it starts).
Installing packages manually in your general python environment will not solve this.

The packages are installed automatically when you install the plugin that requires it.
In case something when wrong during the plugin installation, you can try following the instructions at https://github.com/Crivella/ocr_extension?tab=readme-ov-file#troubleshooting.
Let me know if reinstalling the single/all plugins solves your issue.

In case there are still error during the installation keep a copy/screenshot of the logs of the server (possibly with `set DJANGO_LOG_LEVEL=DEBUG` by editing the script with a text editor) and attach them here so i can have a better idea of what is going on

**Comment by Panwar0** [comment]
*FIRST OF ALL THANKS ALOT FOR STILL REPLYING TO ISSUES*
Alright sir, i will make sure to follow all the steps you've mentioned and I'll then let you know.

**Comment by Panwar0** [comment]
finally after alot of hit and trials after deleting main .orc_translate and pip cache purge i restarted this setup and after waiting and waiting it worked!

**Comment by Panwar0** [comment]
can you suggest me which models to use for cpu only as are best? as i dont have gpu

**Comment by Crivella** [comment]
The only difference between running the models between CPU and GPU is gonna be the speed at which you perform the OCRs + Translations, not the results.

As the combinations i use for:

- jap -> eng:  easyocr/khawhite/staka
- ch -> eng: easyocr/paddleocr/Helsinki (or facebook_m2m)

for the others easyocr/tesseract/facebook_m2m  (but results may vary due to tesseract)

Since the issue has been resolved I am closing this if you have other problem feel free to open a new one or for general question maybe a discussion on the server github page https://github.com/Crivella/ocr_translate
